from typing import Any

class Color:
    value: Any
    def __init__(self, value: int) -> None: ...
    @classmethod
    def default(self) -> int: ...
    @classmethod
    def teal(self) -> int: ...
    @classmethod
    def dark_teal(self) -> int: ...
    @classmethod
    def brand_green(self) -> int: ...
    @classmethod
    def green(self) -> int: ...
    @classmethod
    def dark_green(self) -> int: ...
    @classmethod
    def blue(self) -> int: ...
    @classmethod
    def dark_blue(self) -> int: ...
    @classmethod
    def purple(self) -> int: ...
    @classmethod
    def dark_purple(self) -> int: ...
    @classmethod
    def magenta(self) -> int: ...
    @classmethod
    def dark_magenta(self) -> int: ...
    @classmethod
    def gold(self) -> int: ...
    @classmethod
    def dark_gold(self) -> int: ...
    @classmethod
    def orange(self) -> int: ...
    @classmethod
    def dark_orange(self) -> int: ...
    @classmethod
    def brand_red(self) -> int: ...
    @classmethod
    def red(self) -> int: ...
    @classmethod
    def dark_red(self) -> int: ...
    @classmethod
    def dark_gray(self) -> int: ...
    @classmethod
    def light_gray(self) -> int: ...
    @classmethod
    def blurple(self) -> int: ...
    @classmethod
    def dark_theme(self) -> int: ...
    @classmethod
    def fushia(self) -> int: ...
    @classmethod
    def yellow(self) -> int: ...
