class MessageFlags:
    @classmethod
    def CROSSPOSTED(self): ...
    @classmethod
    def IS_CROSSPOSTED(self): ...
    @classmethod
    def SUPPRESS_EMBEDS(self): ...
    @classmethod
    def SOURCE_MESSAGE_DELETED(self): ...
    @classmethod
    def URGENT(self): ...
    @classmethod
    def HAS_THREAD(self): ...
    @classmethod
    def EPHEMERAL(self): ...
    @classmethod
    def LOADING(self): ...
