from typing import Any

class Intents:
    intents: Any
    def __init__(self, intents: int = ...) -> None: ...
    @staticmethod
    def default() -> int: ...
    @staticmethod
    def all() -> int: ...
    def GUILDS(self): ...
    def GUILD_MEMBERS(self): ...
    def GUILD_BANS(self): ...
    def GUILD_EMOJIS_AND_STICKERS(self): ...
    def GUILD_INTEGRATIONS(self): ...
    def GUILD_WEBHOOKS(self): ...
    def GUILD_INVITES(self): ...
    def GUILD_VOICE_STATES(self): ...
    def GUILD_PRESENCES(self): ...
    def GUILD_MESSAGES(self): ...
    def GUILD_MESSAGE_REACTIONS(self): ...
    def GUILD_MESSAGE_TYPING(self): ...
    def DIRECT_MESSAGES(self): ...
    def DIRECT_MESSAGE_REACTIONS(self): ...
    def DIRECT_MESSAGE_TYPING(self): ...
    def GUILD_SCHEDULED_EVENTS(self): ...
