from typing import Any, List, Optional, Union

class Member:
    from_dict: Any
    guild_id: Any
    def __init__(self, data: dict, guild: Union[int, Any], factory) -> None: ...
    @property
    def user(self): ...
    def nick(self) -> str: ...
    def avatar(self) -> str: ...
    def roles(self) -> None: ...
    def joined_at(self) -> str: ...
    def premium_since(self) -> str: ...
    def deaf(self) -> bool: ...
    def mute(self) -> bool: ...
    def pending(self) -> bool: ...
    def permissions(self) -> dict[str, Any]: ...
    def communication_disabled_until(self) -> str: ...
    def edit(
        self,
        nick: Optional[str] = ...,
        roles: Optional[List[int]] = ...,
        mute: Optional[bool] = ...,
        deaf: Optional[bool] = ...,
        channel_id: Optional[int] = ...,
        timeout: Optional[str] = ...,
        reason: Optional[str] = ...,
    ) -> None: ...
