from discord import __git_sha1__ as __git_sha1__
from discord.types.dict import Dict as Dict
from typing import Optional, Union

def start_logging(flavor: Union[None, int, str, Dict], debug: bool = ...): ...
def print_banner(module: Optional[str] = ...): ...
