from typing import Any

class User:
    from_dict: Any
    def __init__(self, usr: dict) -> None: ...
    def username(self) -> str: ...
    def discriminator(self) -> int: ...
    @property
    def id(self) -> int: ...
    def public_flags(self): ...
    @property
    def bot(self) -> bool: ...
