# Apache-2.0
#
# Copyright 2021 VincentRPS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the LICENSE file for the specific language governing permissions and
# limitations under the License.
from pipelines import nox

STUBGEN_GENERATE = [
    "rpd/__init__.py",
    "rpd/internal/__init__.py",
    "rpd/helpers/__init__.py",
    "rpd/data/types/__init__.py",
]


@nox.session(reuse_venv=True)
def mypy(session: nox.Session) -> None:
    """Perform static type analysis on Python source code."""
    session.install("-r", "requirements.txt", "-r", "dev-requirements.txt")

    _generate_stubs(session)

    session.run("mypy", "-p", nox.main_dir)
    session.run("mypy", "-p")


@nox.session(reuse_venv=True)
def generate_stubs(session: nox.Session) -> None:
    """Generate the stubs for the package."""
    session.install("-r", "dev-requirements.txt")
    _generate_stubs(session)


def _generate_stubs(session: nox.Session) -> None:
    session.run("stubgen", *STUBGEN_GENERATE, "-o", ".", "--include-private", "--no-import")

    stub_paths = [path + "i" for path in STUBGEN_GENERATE]

    session.run("isort", *stub_paths)
    session.run("black", *stub_paths)

    for stub_path in stub_paths:
        with open(stub_path, "r") as fp:
            content = fp.read()

        with open(stub_path, "w") as fp:
            fp.write("# DO NOT EDIT\n")
            fp.write("# This file was generated by `nox -s generate-stubs`\n\n")
            fp.write(content)