from ..channels import Thread as Thread
from ..channels import channel_parse as channel_parse
from .core import Event as Event

class OnChannelCreate(Event):
    def process(self) -> None: ...

class OnChannelUpdate(Event):
    def process(self) -> None: ...

class OnChannelDelete(Event):
    def process(self) -> None: ...

class OnThreadCreate(Event):
    def process(self) -> None: ...

class OnThreadUpdate(Event):
    def process(self) -> None: ...

class OnThreadDelete(Event):
    def process(self) -> None: ...

class OnThreadListSync(Event): ...
